[build]
  command = "npm run build && npm run build:functions"
  publish = "dist"
  functions = "functions"

[functions]
  node_bundler = "none" # Use raw Node.js for CommonJS

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200